action_noise = 0.1
batch_size = 100
criterion = "mse_loss"
gamma = 0.99
gradient_clip_val = inf
polyak = 0.995
[optimizer]
    type = "Adam"
    beta = 0.1
    pi_learning_rate = 0.001
    q_learning_rate = 0.001
    lr_scheduler = false