action_noise = 0.3
batch_size = 2
candidates = 1000  # Number of candidate samples per planning iteration
chunk_size = 2  # Length of sampled chunks/sequences
criterion = "mse_loss"
det_state_size = 200  # Deterministic state size of RSSM
free_nats = 3.0
gamma = 0.99  # Discount factor
global_kl_beta = 0  # KL weight for divergence from global prior
gradient_clip_val = 1000.0
latent_dynamics_model = "ssm"  # Choice of ["rssm", "rnn", "ssm"]
optimization_iters = 10  # Planning optimization iterations
overshooting_distance = 50  # Latent overshooting distance
overshooting_kl_beta = 0  # Latent overshooting KL weight for t > 1
overshooting_reward_scale = 0  # Latent overshooting reward prediction weight for t > 1
planning_horizon = 12
stoch_state_size = 30  # Stochastic state size of RSSM
top_candidates = 100  # Number of top candidates to fit to in CEM

[optimizer]
    type = "Adam"
    beta = 0.1
    learning_rate = 0.001
    lr_scheduler = false

[network_configs]
    activation_function = "relu"
    cell = "GRUCell"
    hidden_layer_sizes = [200,]  # Layer sizes of MLPs in the transition model
    min_std_dev = 0.1
    observation_embedding_size = 1024

