accelerator = false  # Not implemented yet.
checkpoint_interval = 50  # Save agent every number of episodes.
device = "cpu"  # Device to run on: "cpu" or "cuda".
log_dir = "experiments"  # Path to directory where experiments are saved.
log_to_json = true
log_to_tensorboard = true
log_to_wandb = false
disable_video_logging = false  # Disable logging of videos to tensorboard.
num_runs = 1  # Number of runs to perform for each experiment configuration.
resume_from_checkpoint = false  # Path to checkpoint to load agent from.
seed = 0  # Seed from torch and numpy.
seed_episodes = 5  # Numer of initial (random) seed episodes.
test = false  # Only test an agent without training.
test_interval = 25  # Test agent every numer of episodes.
test_episodes = 6  # Number of test episodes to run each test interval.
train_episodes = 1000  # Total number of training episodes to perform.
update_steps = 100  # Number of update steps in the training loop.
verbose = false  # Increase information output.